# Generated by Django 2.2.3 on 2019-07-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='goal_num',
            field=models.PositiveIntegerField(default=0, help_text='How many units is your goal?'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='activity',
            field=models.CharField(help_text='What activity are you performing?', max_length=200),
        ),
        migrations.AlterField(
            model_name='habit',
            name='unit',
            field=models.CharField(help_text='What units are you completing? (steps, lines of code, hours, etc.', max_length=200),
        ),
    ]
