# Generated by Django 2.2.3 on 2019-07-02 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20190701_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyrecord',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['-date_started']},
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='goal_met',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='daily_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DailyRecord'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyrecord',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='habit',
            unique_together={('owner', 'daily_record')},
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='owner_habit',
        ),
    ]
