# Generated by Django 2.2.3 on 2019-07-02 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190702_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='habit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Habit'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyrecord',
            unique_together={('habit', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='habit',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='habit',
            name='daily_record',
        ),
    ]
